### ISSUE TITLE
ERROR WITH SPARK

### ISSUE THREAD

**Issue by GSManganneau** [smallnest/kafka-example-in-scala#3]
Hello, I am trying to use a simple Producer in a spark RDD and I got this error:

java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
    at kafka.producer.ProducerStats.<init>(ProducerStats.scala:24)
    at kafka.producer.ProducerStatsRegistry$$anonfun$1.apply(ProducerStats.scala:34)
    at kafka.producer.ProducerStatsRegistry$$anonfun$1.apply(ProducerStats.scala:34)
    at kafka.utils.Pool.getAndMaybePut(Pool.scala:61)
    at kafka.producer.ProducerStatsRegistry$.getProducerStats(ProducerStats.scala:38)
    at kafka.producer.async.DefaultEventHandler.<init>(DefaultEventHandler.scala:48)
    at kafka.producer.Producer.<init>(Producer.scala:60)
    at org.transatel.spark_kafka.Main$.produce(Main.scala:46)
    at org.transatel.spark_kafka.Main$$anonfun$main$5$$anonfun$apply$1.apply(Main.scala:132)
    at org.transatel.spark_kafka.Main$$anonfun$main$5$$anonfun$apply$1.apply(Main.scala:132)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.rdd.AsyncRDDActions$$anonfun$foreachAsync$1$$anonfun$apply$15.apply(AsyncRDDActions.scala:120)
    at org.apache.spark.rdd.AsyncRDDActions$$anonfun$foreachAsync$1$$anonfun$apply$15.apply(AsyncRDDActions.scala:120)
    at org.apache.spark.SparkContext$$anonfun$37.apply(SparkContext.scala:1992)
    at org.apache.spark.SparkContext$$anonfun$37.apply(SparkContext.scala:1992)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

The code is exactly the same than in your Producer example. Can you help me ? Thank you in advance :)

**Comment by smallnest** [comment]
what version is your Scala?

**Comment by smallnest** [comment]
your spark should use 2.10.x but this project uses 2.11.  you can change this project to use Scala 2.10 to avoid this exception

**Comment by GSManganneau** [comment]
Thanks for the fast answer, how can I change it ? I am using spark 2.10.5 indeed

**Comment by GSManganneau** [comment]
Thank you, it's work.
